#Build the frontend application
FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#Serve the frontend application with nginx server
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
